# 网站图标 Favicon
favicon:
    logo: /img/favicon-32x32.png
    icon16: /img/favicon-16x16.png
    icon32: /img/favicon-32x32.png
    appleTouchIcon: /img/favicon-32x32.png
    webmanifest: /site.webmanifest
    visibilitychange: true
    hidden: failure.ico
    showText: (/≧▽≦/)wmorningBlog
    hideText: (●—●)休息一下啦！

# 加速静态资源 CDN
cdn:
    css:
    js:
        head:
        base:
        async:
        defer:

# 用户信息
user:
    name: 菜鸟书生
    first_name: Blog
    last_name: wmorning
    domain: https://dwmorning.github.io/
    avatar: /img/avatar.jpg
    describe: 网站简介。
    ruleText: 项目均为相关在线展示，网站内容积极向上。

# 导航栏 TopBars
top_bars:
    - title: 主页
      url: /
    - title: 归档
      url: /archives/
      noswup: true
    - title: 项目
      url: /links/
      noswup: true
    - title: 关于
      url: /about/
      noswup: true

# 侧栏 Sidebar
sidebar:
    typedTextPrefix: 优秀的人
    typedText: [ '总是努力翻山越岭' ]
    social: # 社交地址
      # - name: github
      #   icon: fab fa-github
      #   url: https://github.com/dwmorning
    info: 
      - key: leetcode
        val: <a href="/tags/Games" target="_self" rel="nofollow">查看</a>  

# 横幅 Banner
banner:
  use_cover: false
  default:
    type: img
    bgurl: /img/banner.png
    bannerText: Hi my new friend!
    position: top
    fit: cover
  index:
    type: video
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
  archive:
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  comment:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: The magic tree hole
  about:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: About me

# 页脚 Footer
footer:
  powered:
    enable: false
  beian:
    enable: false
    icp: 
  copyrightYear: 2023
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2023 17:00:00
  custom_text: Hosted by <a href="https://github.com" rel="noopener" target="_blank">Github Pages</a>

# 文章 Article
toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1

lazyload: #图片懒加载
    enable: true
archive: #归档页
    type: more # less more
cover: #自定义封面图
    default: /img/block.jpg
    type: img
post_pagination: #上下篇文章
    enable: true
    type: large # large || small
categorie_card: #分类卡片
    enable: true
    len: 2
    list: 

# 关于 About
about:
  # title:        # 标题
  introduction: 大家好，我是菜鸟书生，本博客参考了hexo-theme-async的主题，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。
  # blog:         # 博客信息
  blog: 
    <div class="trm-skill-card trm-scroll-animation trm-active-el" data-scroll="" data-scroll-offset="40">
      <div class="trm-mb-40">
        <div class="trm-skill-header">
          <h6 class="trm-mb-15">Html</h6>
          <span class="trm-label trm-label-light">100%</span></div>
        <div class="trm-progressbar-frame">
          <div class="trm-progressbar p100"></div>
        </div>
      </div>
      <div class="trm-mb-40">
        <div class="trm-skill-header">
          <h6 class="trm-mb-15">CSS</h6>
          <span class="trm-label trm-label-light">100%</span></div>
        <div class="trm-progressbar-frame">
          <div class="trm-progressbar p100"></div>
        </div>
      </div>
      <div>
        <div class="trm-skill-header">
          <h6 class="trm-mb-15">SCSS</h6>
          <span class="trm-label trm-label-light">80%</span></div>
        <div class="trm-progressbar-frame">
          <div class="trm-progressbar p80"></div>
        </div>
      </div>
    </div>
  
  # privacy:      # 隐私权说明    

# 友链 Links
links:
  title: sss        # 标题

# 评论
comment:
  giscus:
    enable: true
    repo: dwmorning/wmorning_blog
    repo-id: R_kgDOJVV2rw
    category: General
    category-id: DIC_kwDOJVV2r84CVy-H
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    lang: zh-CN
    theme: 
      light: light
      dark: dark
#  本地搜索     
search:
  enable: true
  type: local
  trigger: auto
  
# 百度自动推送
baidu_push: true

highlight:
  title: mac
  height_limit: 200
layout:
  page_about: async/about

