# 网站图标 Favicon
favicon:
    logo: /img/favicon-32x32.png
    icon16: /img/favicon-16x16.png
    icon32: /img/favicon-32x32.png
    appleTouchIcon: /img/favicon-32x32.png
    webmanifest: /site.webmanifest
    visibilitychange: true
    hidden: failure.ico
    showText: (/≧▽≦/)wmorningBlog
    hideText: (●—●)休息一下啦！

# 插件 Plugins
assets:
    internal_provider: jsdelivr # local | unpkg | jsdelivr
    third_party_provider: jsdelivr # unpkg | jsdelivr

# 加速静态资源 CDN
cdn:
    css:
    js:
        head:
        base:
        async:
        defer:

# 用户信息
user:
    name: 菜鸟书生
    first_name: Blog
    last_name: wmorning
    domain: https://dwmorning.github.io/
    avatar: /img/avatar.jpg
    describe: 网站简介。
    ruleText: 项目均为相关在线展示，网站内容积极向上。

# 导航栏 TopBars
top_bars:
    - title: 主页
      url: /
    - title: 归档
      url: /archives/
      noswup: true
    - title: 项目
      url: /links/
      noswup: true
    - title: 关于
      url: /about/
      noswup: true

# 侧栏 Sidebar
sidebar:
    typedTextPrefix: 优秀的人
    typedText: [ '总是努力翻山越岭' ]
    social: # 社交地址
      # - name: github
      #   icon: fab fa-github
      #   url: https://github.com/dwmorning
    info: 
      - key: leetcode
        val: <a href="/tags/leetcode" target="_self" rel="nofollow">查看</a>  

# 横幅 Banner
banner:
  use_cover: false
  default:
    type: img
    bgurl: /img/banner.png
    bannerText: Hi my new friend!
    position: top
    fit: cover
  index:
    type: video
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
  archive:
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  comment:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: The magic tree hole
  about:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: About me

# 页脚 Footer
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear: 2023
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2023 17:00:00
  custom_text: Hosted by <a href="https://github.com/dwmorning" rel="noopener" target="_blank">Github Pages</a>

# 文章 Article
toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1

lazyload: #图片懒加载
    enable: true
archive: #归档页
    type: more # less more
cover: #自定义封面图
    type: random
    default: 
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-0jlz9p.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-2ydy76.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-3l9zy3.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-3zkold.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-od95m7.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-j87ldq.jpg # 
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-qzdxd5.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-gj968l.jpg # 
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-4g77y3.jpg # 
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-5gwp58.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-95rrq8.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-28pdry.jpg # 
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-45gjv7.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-0w9qd7.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-8535j1.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-exyxvr.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-g7ormd.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-gp87vd.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-jx5xlw.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-kxwzk6.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-l8m3r2.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-l8m8gy.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-nm7q11.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-0qq2gl.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-72m53y.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-49qy8d.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-6k7z5l.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-45pe95.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-yj7wqk.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-o5x3v7.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-r71zwq.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-rryqkj.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-we61wq.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-zym8vj.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-zyxvqy.jpg #
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-0wz1p6.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-1kr69v.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-3l9kr9.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-5gwrj1.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-6dkmwl.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-8o5v1k.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-9d6g7w.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-953xmw.png
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-gp8wld.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-gp87dq.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-m3dzw1.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-o5x3v7.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-p98ljj.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-qz6p85.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-weyq3p.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-x6l93d.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-y8zeyg.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-z8dlkj.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-z81mqv.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-z81ovo.png
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-z853dv.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-zym8vj.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-zymxpv.jpg
      - //gcore.jsdelivr.net/gh/dwmorning/wmorning-imgs/blogImgs/wallhaven-zymyvj.jpg
post_pagination: #上下篇文章
    enable: true
    type: large # large || small
categorie_card: #分类卡片
    enable: true
    len: 2
    list: 
creative_commons: # 版权信息
    license: by-nc-sa
    language: deed.zh
    post: true
    clipboard: true

# 关于 About
about:
  # title:        # 标题
  introduction: 大家好，我是菜鸟书生，本博客参考了hexo-theme-async的主题，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。
  # blog:         # 博客信息
  blog: 
    <div class="row">
      <div class="col-lg-4"><!-- price table -->
        <div class="trm-price trm-scroll-animation trm-active-el" data-scroll="" data-scroll-offset="40"><!-- card header -->
          <div class="trm-price-header">
            <h6>稀土掘金</h6>
          </div>
          <!-- card header end -->
          <a href="https://juejin.cn/user/3259365820997453" class="trm-btn trm-btn-sm">Go<i class="fas fa-arrow-right"></i></a></div>
        <!-- price table end --></div>
      <div class="col-lg-4"><!-- price table -->
        <div class="trm-price trm-scroll-animation trm-active-el" data-scroll="" data-scroll-offset="40"><!-- card header -->
          <div class="trm-price-header">
            <h6>CSDN</h6>
          </div>
          <!-- card header end -->
          <a href="https://blog.csdn.net/weixin_41360517" class="trm-btn trm-btn-sm">Go<i class="fas fa-arrow-right"></i></a></div>
        <!-- price table end --></div>
      <div class="col-lg-4"><!-- price table -->
        <div class="trm-price trm-scroll-animation trm-active-el" data-scroll="" data-scroll-offset="40"><!-- card header -->
          <div class="trm-price-header">
            <h6>segmentfault</h6>
          </div>
          <!-- card header end -->
          <a href="https://segmentfault.com/u/wmorning" class="trm-btn trm-btn-sm">Go<i class="fas fa-arrow-right"></i></a></div>
        <!-- price table end --></div>
      </div>
  
  # privacy:      # 隐私权说明    

# 友链 Links
links:
  title:        # 标题

# 评论
comment:
  giscus:
    enable: true
    repo: dwmorning/wmorning_blog
    repo-id: R_kgDOJVV2rw
    category: General
    category-id: DIC_kwDOJVV2r84CVy-H
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    lang: zh-CN
    theme: 
      light: light
      dark: dark
#  本地搜索     
search:
  enable: true
  type: local
  trigger: auto
  
# 百度自动推送
baidu_push: true

highlight:
  title: default
  height_limit: 200

# 自定义模板 Layout
layout:
  page_archive: async/archive
  # page_about: async/about

